# Generated by Django 5.1.7 on 2025-04-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='medical_store',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medical_store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='medical_store',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='MediRegistration',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
