# Generated by Django 5.1.7 on 2025-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reminder_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
