# Generated by Django 5.1.7 on 2025-04-23 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_prescription_delivery_address_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.CreateModel(
            name='CustomerIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
