# Generated by Django 5.1.7 on 2025-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_order_status_alter_prescription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='reminder_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
