# Generated by Django 5.1.7 on 2025-04-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_prescription_reminder_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='image',
        ),
    ]
