# Generated by Django 5.1.7 on 2025-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_prescription_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerissue',
            name='status',
        ),
        migrations.AddField(
            model_name='customerissue',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
