# Generated by Django 5.1.7 on 2025-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_remove_customerissue_status_customerissue_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerissue',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerissue',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
