# Generated by Django 5.1.7 on 2025-04-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_customerissue_is_read_alter_customerissue_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
