# Generated by Django 5.2.1 on 2025-05-31 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_alter_prescription_status'),
        ('medical', '0007_alter_medicalissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.medicine'),
        ),
    ]
