# Generated by Django 5.2.1 on 2025-06-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_order_medicine'),
        ('medical', '0008_medicine_prescription_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.medicine'),
        ),
    ]
