# Generated by Django 5.1.7 on 2025-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_photo', models.ImageField(upload_to='owner_photos/')),
                ('owner_id_proof', models.FileField(upload_to='owner_id_proofs/')),
                ('pharmacist_name', models.CharField(max_length=100)),
                ('pharmacist_photo', models.ImageField(upload_to='pharmacist_photos/')),
                ('address', models.TextField()),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Delhi', 'Delhi')], max_length=100)),
                ('pincode', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('shop_no', models.CharField(max_length=50)),
                ('license_no', models.CharField(max_length=100)),
                ('license_photo', models.ImageField(upload_to='license_photos/')),
                ('intimation_letter_photo', models.ImageField(upload_to='intimation_letters/')),
                ('food_license_photo', models.ImageField(upload_to='food_licenses/')),
                ('bank_account_no', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('passbook_photo', models.ImageField(upload_to='passbook_photos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
