# Generated by Django 5.1.7 on 2025-04-21 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_prescription'),
        ('medical', '0003_patientuser_remove_invoice_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.AlterField(
            model_name='prescriptionbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptionbill',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='Customer.prescription'),
        ),
        migrations.DeleteModel(
            name='PatientUser',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
