# Generated by Django 5.1.7 on 2025-04-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_remove_prescription_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionbill',
            old_name='patient',
            new_name='customer',
        ),
    ]
