# Generated by Django 5.1.7 on 2025-04-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_rename_patient_prescriptionbill_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.mediregistration')),
            ],
        ),
    ]
