# Generated by Django 5.1.7 on 2025-04-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_medicalissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalissue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
