# Generated by Django 5.2.1 on 2025-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_alter_medicalissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=True),
        ),
    ]
